/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CropSummary: typeof import('./components/CropSummary.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Item: typeof import('./components/Item.vue')['default']
    Product: typeof import('./components/Product.vue')['default']
    ProductList: typeof import('./components/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
